### ISSUE TITLE
Consider deploying the source along the binary

### ISSUE THREAD

**Issue by victornoel** [dajudge/kindcontainer#1]
Hi,

It would be great if you could consider deploying the sources next to the jar.

By the way are you aware that bintray.com is becoming read-only starting tomorrow? See https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by dajudge** [comment]
Should be there now w/ 0.0.13. Let me know if it doesn't work for you.

Also moved to Maven Central w/ 0.0.13

**Comment by victornoel** [comment]
@dajudge very nice, thx!
